name: ADF validation Pipeline

on:
  pull_request:
      types:
        - opened
      branches:
        - 'main'
  workflow_dispatch:
  
  # workflow_call: 
  #   inputs:
  #         parametername:
  #           required: true
  #           type: string
        
jobs:
  build:
    environment: Dev
    name: Build ADF Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBS_ID }}
          enable-AzPSSession: true
  
      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
            
      - name: Setup Node.js environment
        uses: actions/setup-node@v5.0.0
          
      - name: Install npm
        run: npm install

      - name: Validate
        run: npm run build validate $(pwd) /subscriptions/${{ secrets.SUBSCRIPTION_ID }}/resourceGroups/Akshita/providers/Microsoft.DataFactory/factories/ATCOTestADF01
        
      - name: Generate ARM Template
        run: npm run build export $(pwd) /subscriptions/${{ secrets.SUBSCRIPTION_ID }}/resourceGroups/Akshita/providers/Microsoft.DataFactory/factories/ATCOTestADF01 "ArmTemplate"
      
      - name: List files in current directory
        run: ls -R ArmTemplate/
        
      - name: List the updated parameters
        run: cat ArmTemplate/ARMTemplateParametersForFactory.json

      - name: Display contents of parameters.updated.json
        run: rm -rf ArmTemplate
